### ISSUE TITLE
FS Project Review

### ISSUE THREAD

**Issue by HRemonen** [alexha11/AI-Image-Generator#6]
This is a review for your fullstack-project. You do not need to implement possible suggestions for improvement mentioned here to receive your credits.

--- 

## User experience

- The UI is clean and simple. I like that!
- Now that you created the user functionalities, it would be good practice to "hide" only logged in user features from those users who has not logged in. If the user can't do something, the UI should not be there for the user in the first place, if that makes sense. For example the user "profile" page and creation of posts.
- I like the new functionalities you created, the application seems to function better now than before!

## Code

- Plus for using AWS, Docker, OpenAI and Cloudinary for your application. Shows great passion for learning new things outside the course scope.
- Production code should be cleaned from console logs
- If you would like to get rid of the try - catch blocks you could use express-async-errors package. I think it will contribute to a cleaner repo. Express v5 will also fix this I think.
- I think it would be benefitial to extract the business logic from the routes to own service functions, makes the code cleaner and easier to read.
- On the frontend there are empty components, such as `src/components/Search.jsx`
- Commented out code should be removed, it can always be fetched from the version control later on if needed.
- DO NOT nest rendering React components [it's a major violation of React](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-unstable-nested-components.md). For example at [Home.jsx](https://github.com/alexha11/AI-Image-Generator/blob/6e064c490573578eb61c4041a52edafa98ed75e2/client/src/pages/Home.jsx#L55C1-L61C4). These kind of issues can be easily avoided just configuring eslint properly.

## Conclusion

Thank you for the video demo, it was nice. Also you've done great stuff since the last time I checked your repository. The project shows unprompted willingness for new technologies and adapting them in your own solution. You will be getting your credits in the near future.

**Comment by alexha11** [comment]
Thank you for your kind words and very detailed and comprehensive suggestions! They provide valuable insight for me to improve my application.
